name: dbt CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake

     
      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "advworks:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: \"${{ secrets.SNOWFLAKE_ACCOUNT }}\"" >> ~/.dbt/profiles.yml
          echo "      user: \"${{ secrets.SNOWFLAKE_USER }}\"" >> ~/.dbt/profiles.yml
          echo "      password: \"${{ secrets.SNOWFLAKE_PASSWORD }}\"" >> ~/.dbt/profiles.yml
          echo "      role: \"${{ secrets.SNOWFLAKE_ROLE }}\"" >> ~/.dbt/profiles.yml
          echo "      database: \"${{ secrets.SNOWFLAKE_DATABASE }}\"" >> ~/.dbt/profiles.yml
          echo "      warehouse: \"${{ secrets.SNOWFLAKE_WAREHOUSE }}\"" >> ~/.dbt/profiles.yml
          echo "      schema: \"${{ secrets.SNOWFLAKE_SCHEMA }}\"" >> ~/.dbt/profiles.yml
          echo "      threads: 4" >> ~/.dbt/profiles.yml
          echo "      client_session_keep_alive: false" >> ~/.dbt/profiles.yml

      - name: Install dbt packages
        run: dbt deps --project-dir . --profiles-dir ~/.dbt

      - name: Compile project
        run: dbt compile --project-dir . --profiles-dir ~/.dbt

      - name: Run dbt models
        run: dbt run --project-dir . --profiles-dir ~/.dbt

      - name: Run dbt tests
        run: dbt test --project-dir . --profiles-dir ~/.dbt